### ISSUE TITLE
suspicious login attempt blocked

### ISSUE THREAD

**Issue by atharvakadlag** [b31ngd3v/MyIGBot#15]
```
Traceback (most recent call last):
  File "/Users/xxx/MyIGBot/usage.py", line 3, in <module>
    bot = MyIGBot('correct-username', 'correct-password')
  File "/Users/xxx/MyIGBot/myigbot.py", line 178, in __init__
    self.sessionid = login_response.headers['Set-Cookie'].split('sessionid=')[1].split(';')[0]                
IndexError: list index out of range
```
I get this error, I am not sure what to do. Help will be appreciated.

Update:
    the error disappeared, now it says login failed. instagram sent me a mail saying suspicious login blocked. need a workaround on this,

**Comment by sleepingforest20** [comment]
update your script,

**Comment by kass507** [comment]
I have the same problem. I only receive the code by mail.
Note: My account does not have two-step authentication. I also have the package updated.
