### ISSUE TITLE
Login Failed

### ISSUE THREAD

**Issue by lilcheti** [b31ngd3v/MyIGBot#20]
no matter wich account i use it says :
[✗] Login Failed!
i already tested three ig accounts and with or without proxies

**Comment by ghost** [comment]
Try to login in the browser (incognito)

**Comment by lilcheti** [comment]
Traceback (most recent call last):
  File "/Users/farbod/Documents/myig.py", line 3, in <module>
    bot = MyIGBot('armo.cases', 'MA PASS')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/myigbot/__init__.py", line 61, in __init__
    self.csrf_token = cookie_jar['csrftoken']
KeyError: 'csrftoken'

now getting this error

**Comment by ghost** [comment]
hide your password buddy @rimthekid

**Comment by ghost** [comment]
Looks like @asarra faced the same issue yesterday, waiting for your (@asarra) PR :)

**Comment by asarra** [comment]
> 
> 
> Looks like @asarra faced the same issue yesterday, waiting for your (@asarra) PR :)

Sure, I have also added the functionality to upload a video to it. But it is gonna take some time until I can code again. Probably a week

**Comment by m2083902** [comment]
tfk are you talking


În mie., 30 dec. 2020 la 15:23, asarra <notifications@github.com> a scris:

**Comment by asarra** [comment]
Seems like this will take longer. @el-pr0f3ss0r I would like to send you my code. You can check the differences for yourself then. What way of communication should we use for that?

**Comment by blizzak1234** [comment]
hi! 
any news, guys?
I can't login with neither 2-factor authentification nor basic way... =(

**Comment by lggg123** [comment]
I am also having trouble logging in.
