### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by 89z** [b31ngd3v/MyIGBot#34]
Using this code:

~~~py
from myigbot import MyIGBot
bot = MyIGBot('srpen6', 'PASSWORD')
~~~

I get this result:

~~~
Traceback (most recent call last):
  File "D:\Desktop\ig.py", line 4, in <module>
    bot = MyIGBot('srpen6', 'PASSWORD')
  File "C:\python\lib\site-packages\myigbot\__init__.py", line 178, in __init__
    self.sessionid = login_response.headers['Set-Cookie'].split('sessionid=')[1].split(';')[0]
IndexError: list index out of range
~~~

**Comment by 89z** [comment]
Closing this in favor of my own package:

https://github.com/89z/mech/tree/master/instagram
