### ISSUE TITLE
Can't initialize the bot, because of some cookies issue

### ISSUE THREAD

**Issue by alexisbcz** [b31ngD3v/MyIGBot#4]
Hi !

I can't initialize the bot because of some cookies issue.
Here is my code : 
`from myigbot import MyIGBot

bot = MyIGBot('my_username', 'my_password')`

I receive this error message : 

`
Traceback (most recent call last):
  File "usage.py", line 3, in <module>
    bot = MyIGBot('my_username', 'my_password')
  File "C:\Users\Alex\Downloads\MyIGBot-0.2.4\myigbot.py", line 35, in __init__
    csrf = response.cookies['csrftoken']
  File "C:\Users\Alex\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\requests\cookies.py", line 328, in __getitem__    
    return self._find_no_duplicates(name)
  File "C:\Users\Alex\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\requests\cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"
`

**Comment by b31ngD3v** [comment]
Did you replaced my_username with your username and my_password with your password, before running it?

**Comment by alexisbcz** [comment]
Of course

**Comment by b31ngD3v** [comment]
I'll recommend you to download the module.
`pip install myigbot`

**Comment by alexisbcz** [comment]
It's already done, I actually used both python's module and the other one.

I temporarily got manually a csrf token that I replaced in the code.

**Comment by b31ngD3v** [comment]
Is it working after replacing the line ?

**Comment by alexisbcz** [comment]
Yes, it is. But I regret I can't get the cookie automatically. Anyway, I close this issue.
