### ISSUE TITLE
ModuleNotFoundError: No module named 'cv2' (Details Below)

### ISSUE THREAD

**Issue by NomanBaigA** [b31ngd3v/MyIGBot#46]
Traceback (most recent call last):
  File "c:\Users\USERNAME\Desktop\MyIGBot-main\try1.py", line 1, in <module>    
    from myigbot import MyIGBot
  File "c:\Users\USERNAME\Desktop\MyIGBot-main\myigbot.py", line 10, in <module>
    from utils import get_media_duration
  File "c:\Users\USERNAME\Desktop\MyIGBot-main\utils.py", line 1, in <module>   
    import cv2
ModuleNotFoundError: No module named 'cv2'

**Comment by Shrihari-cRypTo** [comment]
Have you pip installed your cv2 module?

**Comment by drdoof2019** [comment]
`pip install opencv-python`
This is it. if you just paste error to google, that is first result.

**Comment by Shrihari-cRypTo** [comment]
maybe the path in which u installed may not in the PATH variable
Check it also usually CV2 requires media pack to be enabled on windows

**Comment by NomanBaigA** [comment]
Thank you, everyone
